name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        pip install -r app/requirements.txt



    steps:
      - uses: action/checkout@v1

      - name: Push Docker image
      
        run: |
          echo "${{ secrets.DOCKERPSSWRD }}" | docker login -u "spydafrommrod4" --password-stdin
          docker image build -t spydafrommrod4/projetdit .
          docker push spydafrommrod4/projetdit:v2